name: Build and deploy Python app to Azure Web App - RedScore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./
            !venv/  # Exclude virtual environment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App as loose files
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'RedScore'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F1C1F0477B2A4F95A005D12FF212284B }}
          package: .  # Deploy as loose files

      - name: Enable build during deployment (optional)
        uses: azure/appservice-settings@v1
        with:
          app-name: 'RedScore'
          settings: |
            SCM_DO_BUILD_DURING_DEPLOYMENT=true
